# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(579, 510)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(10, 100, 561, 301))
        self.tableView.setObjectName("tableView")
        self.del_row = QtWidgets.QPushButton(self.centralwidget)
        self.del_row.setGeometry(QtCore.QRect(170, 420, 161, 41))
        self.del_row.setObjectName("del_row")
        self.add_row = QtWidgets.QPushButton(self.centralwidget)
        self.add_row.setGeometry(QtCore.QRect(10, 420, 151, 41))
        self.add_row.setObjectName("add_row")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 101, 16))
        self.label.setObjectName("label")
        self.select_table = QtWidgets.QComboBox(self.centralwidget)
        self.select_table.setGeometry(QtCore.QRect(120, 10, 171, 21))
        self.select_table.setObjectName("select_table")
        self.filter_arg = QtWidgets.QLineEdit(self.centralwidget)
        self.filter_arg.setGeometry(QtCore.QRect(60, 50, 113, 20))
        self.filter_arg.setObjectName("filter_arg")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 48, 16))
        self.label_2.setObjectName("label_2")
        self.filter_col = QtWidgets.QComboBox(self.centralwidget)
        self.filter_col.setGeometry(QtCore.QRect(240, 50, 171, 21))
        self.filter_col.setObjectName("filter_col")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(180, 50, 51, 16))
        self.label_3.setObjectName("label_3")
        self.button_apply_filter = QtWidgets.QPushButton(self.centralwidget)
        self.button_apply_filter.setGeometry(QtCore.QRect(420, 50, 75, 23))
        self.button_apply_filter.setObjectName("button_apply_filter")
        self.button_cancel_filter = QtWidgets.QPushButton(self.centralwidget)
        self.button_cancel_filter.setGeometry(QtCore.QRect(500, 50, 75, 23))
        self.button_cancel_filter.setObjectName("button_cancel_filter")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.del_row.setText(_translate("MainWindow", "Удалить выбранную строку"))
        self.add_row.setText(_translate("MainWindow", "Добавить пустую строку"))
        self.label.setText(_translate("MainWindow", "Выберите таблицу"))
        self.label_2.setText(_translate("MainWindow", "Фильтр"))
        self.label_3.setText(_translate("MainWindow", "По полю:"))
        self.button_apply_filter.setText(_translate("MainWindow", "Применить"))
        self.button_cancel_filter.setText(_translate("MainWindow", "Отменить"))
